name: Bug Report
description: Report a bug in beacon-skill
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Report a Bug
        Bug fixes can earn RTC bounties!

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - BeaconClient
        - Relay System
        - Key Management
        - Atlas Discovery
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Install `pip install beacon-skill`
        2. Run...
        3. See error...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: beacon-skill version
      placeholder: "1.4.0"

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell
